# Generated by Django 3.2.20 on 2023-07-26 21:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "secand_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("image", models.ImageField(upload_to="images/banners")),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default="True",
                        max_length=10,
                    ),
                ),
                (
                    "main_title_clases",
                    models.CharField(
                        choices=[
                            ("white-color font-weak", "white-color font-weak"),
                            ("white-color", "white-color"),
                            ("None", "None"),
                            ("primary-color", "primary-color"),
                        ],
                        default="None",
                        max_length=100,
                    ),
                ),
                (
                    "secand_title_clases",
                    models.CharField(
                        choices=[
                            ("white-color font-weak", "white-color font-weak"),
                            ("white-color", "white-color"),
                            ("None", "None"),
                            ("primary-color", "primary-color"),
                        ],
                        default="None",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BannerSecand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "secand_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("image", models.ImageField(upload_to="images/banners")),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default="True",
                        max_length=10,
                    ),
                ),
                (
                    "main_title_clases",
                    models.CharField(
                        choices=[
                            ("white-color font-weak", "white-color font-weak"),
                            ("white-color", "white-color"),
                            ("None", "None"),
                            ("primary-color", "primary-color"),
                        ],
                        default="None",
                        max_length=100,
                    ),
                ),
                (
                    "secand_title_clases",
                    models.CharField(
                        choices=[
                            ("white-color font-weak", "white-color font-weak"),
                            ("white-color", "white-color"),
                            ("None", "None"),
                            ("primary-color", "primary-color"),
                        ],
                        default="None",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Read", "Read"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordernumber", models.IntegerField()),
                ("question", models.CharField(max_length=200)),
                ("answer", ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default="True",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=50)),
                ("comment", models.CharField(blank=True, max_length=250)),
                ("rate", models.IntegerField(default=1)),
                ("ip", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("New", "New"), ("True", "True"), ("False", "False")],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("smtpserver", models.CharField(blank=True, max_length=50, null=True)),
                ("smtpemail", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "smtppassword",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("smtpport", models.CharField(blank=True, max_length=5, null=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("facebook", models.CharField(blank=True, max_length=150, null=True)),
                ("instgram", models.CharField(blank=True, max_length=150, null=True)),
                ("twitter", models.CharField(blank=True, max_length=150, null=True)),
                ("linkdin", models.CharField(blank=True, max_length=150, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "aboutus",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "contact",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "references",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("site_views", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default="True",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
