# Generated by Django 3.2.20 on 2023-07-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="images/users/img1.jpg", upload_to="images/users/"
            ),
        ),
    ]
