# Generated by Django 3.2.20 on 2023-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/users/img1.jpg",
                null=True,
                upload_to="images/users/",
            ),
        ),
    ]
